uploads = []

[[generated]]
id = "4yi_dAFMgieNgb8uLDdc6"
uri = "file://artifacts/shadow-habits/src/assets/character-infinity.png"
type = "image"
title = "Infinity Mentor portrait"

[[generated]]
id = "3tLIabrIBmMmkrBBlVvKo"
uri = "file://artifacts/shadow-habits/src/assets/character-dark.png"
type = "image"
title = "Dark King portrait"

[[generated]]
id = "sGrvf1lrx2ulwB5-wMdxh"
uri = "file://artifacts/shadow-habits/src/assets/character-energy.png"
type = "image"
title = "Energy Hero portrait"

[[outputs]]
id = "0UAsr7-ijvmHnk0O18sia"
uri = "file://artifacts/shadow-habits/src/assets/character-megumi.png"
type = "image"
title = "anime character portrait green haired serious student portrait"

[[outputs]]
id = "sPBslhnio-vBstuUd0xG1"
uri = "file://artifacts/shadow-habits/src/assets/character-nobara.png"
type = "image"
title = "anime character portrait confident female with short hair and hammer"

[[outputs]]
id = "iFaS3nYis198r8QAlHfZb"
uri = "file://artifacts/shadow-habits/src/assets/character-maki.png"
type = "image"
title = "anime character portrait strong female with dark hair and uniform"

[[outputs]]
id = "nYE3SAqipe-_vAf-fC9vC"
uri = "file://artifacts/shadow-habits/src/assets/character-inumaki.png"
type = "image"
title = "anime character portrait silver haired character high collar"

[[outputs]]
id = "MOzn6VuJa4AFXGz8GnhU2"
uri = "file://artifacts/shadow-habits/src/assets/character-toji.png"
type = "image"
title = "anime character portrait muscular dark haired man serious assassin"

[[outputs]]
id = "ulcs7uUYqrZDnHRTC9cBz"
uri = "file://artifacts/shadow-habits/src/assets/character-nanami.png"
type = "image"
title = "anime character portrait blond man glasses suit serious"

[[outputs]]
id = "VIzzPGCaf0sobU9mrvZQx"
uri = "file://artifacts/shadow-habits/src/assets/character-gojo.png"
type = "image"
title = "anime character portrait white haired smiling teacher blindfold"

[[outputs]]
id = "8aYMU9ExqYRO6v7FjWIMY"
uri = "file://artifacts/shadow-habits/src/assets/character-yuta.png"
type = "image"
title = "anime character portrait black haired young man special grade sword"
