// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/AccessibilityReadability.tsx": () => import("../components/mockups/login-variants/AccessibilityReadability.tsx"),
  "./components/mockups/login-variants/CenteredImmersive.tsx": () => import("../components/mockups/login-variants/CenteredImmersive.tsx"),
  "./components/mockups/login-variants/InfoHierarchy.tsx": () => import("../components/mockups/login-variants/InfoHierarchy.tsx"),
  "./components/mockups/login-variants/InteractionAffordance.tsx": () => import("../components/mockups/login-variants/InteractionAffordance.tsx"),
  "./components/mockups/login-variants/SplitPanel.tsx": () => import("../components/mockups/login-variants/SplitPanel.tsx"),
  "./components/mockups/login-variants/VerticalStack.tsx": () => import("../components/mockups/login-variants/VerticalStack.tsx")
};
